In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 


df = pd.read_csv('Social_media_impact_on_life.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   str
 1   Age                          4500 non-null   int64
 2   Gender                       4500 non-null   str
 3   Academic_Level               4500 non-null   str
 4   Primary_Platform             4500 non-null   str
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   str
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   str
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   str
dtypes: bool(1), float64(5), int64(3), str(7)
memory usage: 531.9 KB

# Columnas que tenemos : 

- Student_id / Age / Gender / Academic_Level
- Primary_Platform : red social mas usada 
- Daily_Usage_Hours : Media de horas diarias
- Weekend_Extra_Hours : Media extra de horas diarias en fin de semana
- Device_Type
- Sleep_Duration_Hours 
- Sleep_Quality_Score 
- Late_Night_Usage
- Social_Comparison_Frequency
- Perceived_Stress_Score : Nivel de estres percivido 
- Mental_Health_Index
- Academic_Performance_GPA
- Overall_Impact

In [49]:
df = df.drop(columns='Student_ID') #Se borra el id por que es irrelevante

- Gender : Mapear a 0/1 (Male / Female) 
- Academic_Level : Mapear a 0/1 (High School / Undergraduate / Postgraduate )  
- Perceived_Stress_Score / Academic_Performance_GPA : Rellenar nulos
- Primary_Platform : Mapear a 0/1 (Snapchat / Instagram / TikTok / Youtube / Linkedin)
- Device_Type : Mapear a 0/1 (Smartphone / Tablet / Laptop/PC)
- Social_Comparison_Frequency : Mapear a 0/1 (Never / Sometimes / Frequently / Always)
- Overall_Impact : ------

In [50]:
df['Gender'] = df['Gender'].map({ #Se mapea el genero (Male = 0 , Female = 1)
    'Male' : 0,
    'Female' : 1
})

df['Academic_Level'] = df['Academic_Level'].map({ #Se mapea el nivel escolar siguiendo su propia escala entre 0-1
    'High School' : 0,
    'Undergraduate' : 0.5,
    'Postgraduate' : 1
})

df['Social_Comparison_Frequency'] = df['Social_Comparison_Frequency'].map({
    'Never' : 0,
    'Sometimes' : 0.33,
    'Frequently' : 0.66,
    'Always' : 1
})
df

,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,19,1.0,0.5,Snapchat,7.5,1.5,Smartphone,5.9,2,True,1.00,20.0,73,2.73,Neutral
1,19,1.0,0.5,Instagram,4.6,1.3,Smartphone,7.9,3,True,0.33,17.0,90,3.21,Beneficial
2,17,1.0,0.0,TikTok,10.9,1.7,Smartphone,5.2,1,True,0.66,18.0,70,3.00,Neutral
3,16,1.0,0.0,YouTube,6.0,2.3,Tablet,7.6,4,True,0.33,15.0,82,3.42,Beneficial
4,17,0.0,0.0,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,0.00,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,16,0.0,0.0,YouTube,5.8,1.2,Smartphone,7.8,3,True,0.33,11.0,79,2.85,Beneficial
4496,19,1.0,0.5,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,0.66,9.0,83,3.37,Beneficial
4497,19,0.0,0.5,Instagram,7.7,1.1,Smartphone,6.0,2,True,0.66,13.0,73,3.16,Beneficial
4498,16,0.0,0.0,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,0.33,22.0,87,3.50,Beneficial
4499,24,0.0,0.5,Instagram,1.8,2.1,Smartphone,6.8,3,True,0.66,10.0,98,3.73,Beneficial

In [51]:
df = pd.get_dummies(df, columns=['Primary_Platform','Device_Type'], drop_first=True)
df

,Age,Gender,Academic_Level,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,...,Academic_Performance_GPA,Overall_Impact,Primary_Platform_LinkedIn,Primary_Platform_Reddit,Primary_Platform_Snapchat,Primary_Platform_TikTok,Primary_Platform_X (Twitter),Primary_Platform_YouTube,Device_Type_Smartphone,Device_Type_Tablet
0,19,1.0,0.5,7.5,1.5,5.9,2,True,1.00,20.0,...,2.73,Neutral,False,False,True,False,False,False,True,False
1,19,1.0,0.5,4.6,1.3,7.9,3,True,0.33,17.0,...,3.21,Beneficial,False,False,False,False,False,False,True,False
2,17,1.0,0.0,10.9,1.7,5.2,1,True,0.66,18.0,...,3.00,Neutral,False,False,False,True,False,False,True,False
3,16,1.0,0.0,6.0,2.3,7.6,4,True,0.33,15.0,...,3.42,Beneficial,False,False,False,False,False,True,False,True
4,17,0.0,0.0,3.3,2.6,7.6,4,True,0.00,16.0,...,3.41,Beneficial,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,16,0.0,0.0,5.8,1.2,7.8,3,True,0.33,11.0,...,2.85,Beneficial,False,False,False,False,False,True,True,False
4496,19,1.0,0.5,3.8,3.0,6.6,3,False,0.66,9.0,...,3.37,Beneficial,True,False,False,False,False,False,True,False
4497,19,0.0,0.5,7.7,1.1,6.0,2,True,0.66,13.0,...,3.16,Beneficial,False,False,False,False,False,False,True,False
4498,16,0.0,0.0,4.6,3.3,7.1,3,False,0.33,22.0,...,3.50,Beneficial,True,False,False,False,False,False,False,False
4499,24,0.0,0.5,1.8,2.1,6.8,3,True,0.66,10.0,...,3.73,Beneficial,False,False,False,False,False,False,True,False

In [52]:
df['Overall_Impact'] = df['Overall_Impact'].map({
    'Negative' : 0,
    'Neutral' : 0.5,
    'Beneficial' : 1
})
df

,Age,Gender,Academic_Level,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,...,Academic_Performance_GPA,Overall_Impact,Primary_Platform_LinkedIn,Primary_Platform_Reddit,Primary_Platform_Snapchat,Primary_Platform_TikTok,Primary_Platform_X (Twitter),Primary_Platform_YouTube,Device_Type_Smartphone,Device_Type_Tablet
0,19,1.0,0.5,7.5,1.5,5.9,2,True,1.00,20.0,...,2.73,0.5,False,False,True,False,False,False,True,False
1,19,1.0,0.5,4.6,1.3,7.9,3,True,0.33,17.0,...,3.21,1.0,False,False,False,False,False,False,True,False
2,17,1.0,0.0,10.9,1.7,5.2,1,True,0.66,18.0,...,3.00,0.5,False,False,False,True,False,False,True,False
3,16,1.0,0.0,6.0,2.3,7.6,4,True,0.33,15.0,...,3.42,1.0,False,False,False,False,False,True,False,True
4,17,0.0,0.0,3.3,2.6,7.6,4,True,0.00,16.0,...,3.41,1.0,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,16,0.0,0.0,5.8,1.2,7.8,3,True,0.33,11.0,...,2.85,1.0,False,False,False,False,False,True,True,False
4496,19,1.0,0.5,3.8,3.0,6.6,3,False,0.66,9.0,...,3.37,1.0,True,False,False,False,False,False,True,False
4497,19,0.0,0.5,7.7,1.1,6.0,2,True,0.66,13.0,...,3.16,1.0,False,False,False,False,False,False,True,False
4498,16,0.0,0.0,4.6,3.3,7.1,3,False,0.33,22.0,...,3.50,1.0,True,False,False,False,False,False,False,False
4499,24,0.0,0.5,1.8,2.1,6.8,3,True,0.66,10.0,...,3.73,1.0,False,False,False,False,False,False,True,False

In [64]:

perceived_stress_score_median = df['Perceived_Stress_Score'].median()

df['Perceived_Stress_Score'] = df['Perceived_Stress_Score'].fillna(perceived_stress_score_median)

df['Academic_Performance_GPA'] = df['Academic_Performance_GPA'].fillna(
    df.groupby('Academic_Level')['Academic_Performance_GPA'].transform('median'))

print(df.isnull().sum())

Student_ID                     0
Age                            0
Gender                         0
Academic_Level                 0
Primary_Platform               0
Daily_Usage_Hours              0
Weekend_Extra_Hours            0
Device_Type                    0
Sleep_Duration_Hours           0
Sleep_Quality_Score            0
Late_Night_Usage               0
Social_Comparison_Frequency    0
Perceived_Stress_Score         0
Mental_Health_Index            0
Academic_Performance_GPA       0
Overall_Impact                 0
dtype: int64